# Generated by Django 5.2.17 on 2026-09-07 21:05

import apps.core.uuid7
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("affiliation", "0001_initial"),
        ("catalog", "0001_initial"),
        ("marketplace", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Commande",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("numero", models.CharField(max_length=32, unique=True)),
                (
                    "total_ht",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "total_tva",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "total_ttc",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "frais_livraison",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("confirmee", "Confirmée"),
                            ("payee", "Payée"),
                            ("livree", "Livrée"),
                            ("cloturee", "Clôturée"),
                            ("annulee", "Annulée"),
                        ],
                        db_index=True,
                        default="brouillon",
                        max_length=16,
                    ),
                ),
                ("code_apporteur", models.CharField(blank=True, max_length=12)),
                ("livree_le", models.DateTimeField(blank=True, null=True)),
                (
                    "acheteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commandes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "apporteur_n1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commandes_n1",
                        to="affiliation.apporteur",
                    ),
                ),
                (
                    "apporteur_n2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commandes_n2",
                        to="affiliation.apporteur",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revendeur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commandes",
                        to="affiliation.revendeur",
                    ),
                ),
            ],
            options={
                "verbose_name": "commande",
                "ordering": ["-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="SousCommande",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "total_ht",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "total_tva",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "total_ttc",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "taux_commission",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "commission_plateforme",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("acceptee", "Acceptée"),
                            ("preparee", "Préparée"),
                            ("expediee", "Expédiée"),
                            ("livree", "Livrée"),
                            ("annulee", "Annulée"),
                        ],
                        db_index=True,
                        default="en_attente",
                        max_length=16,
                    ),
                ),
                ("livree_le", models.DateTimeField(blank=True, null=True)),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="marketplace.boutique",
                    ),
                ),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sous_commandes",
                        to="orders.commande",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "sous-commande",
                "verbose_name_plural": "sous-commandes",
                "ordering": ["-cree_le"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_all_tenants", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Retour",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("motif", models.TextField()),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("demande", "Demandé"),
                            ("accepte", "Accepté"),
                            ("refuse", "Refusé"),
                            ("rembourse", "Remboursé"),
                        ],
                        default="demande",
                        max_length=16,
                    ),
                ),
                (
                    "montant_rembourse",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="marketplace.boutique",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sous_commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retours",
                        to="orders.souscommande",
                    ),
                ),
            ],
            options={
                "verbose_name": "retour",
                "ordering": ["-cree_le"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_all_tenants", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="LigneCommande",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("libelle", models.CharField(max_length=200)),
                ("quantite", models.DecimalField(decimal_places=4, max_digits=14)),
                ("pu_ttc", models.DecimalField(decimal_places=2, max_digits=12)),
                ("taux_tva", models.DecimalField(decimal_places=4, max_digits=5)),
                (
                    "remise",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="marketplace.boutique",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.variante",
                    ),
                ),
                (
                    "sous_commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="orders.souscommande",
                    ),
                ),
            ],
            options={
                "verbose_name": "ligne de commande",
                "verbose_name_plural": "lignes de commande",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_all_tenants", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="souscommande",
            constraint=models.UniqueConstraint(
                fields=("commande", "boutique"), name="une_sous_commande_par_boutique"
            ),
        ),
    ]
