# Generated by Django 5.2.17 on 2026-09-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commande",
            name="operation_id",
            field=models.UUIDField(
                blank=True,
                help_text="Clé d'idempotence du tunnel de commande (ADR-004).",
                null=True,
                unique=True,
            ),
        ),
    ]
