# Generated by Django 5.2.17 on 2026-09-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_commande_operation_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="commande",
            name="adresse_livraison",
            field=models.CharField(
                blank=True,
                help_text="Texte libre : le découpage en zones et tarifs relève du lot 2.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="note",
            field=models.TextField(
                blank=True, help_text="Précisions de l'acheteur pour le marchand."
            ),
        ),
    ]
