# Generated by Django 5.2.17 on 2026-09-30 09:14

import apps.core.uuid7
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0007_confiance_et_versement"),
        ("orders", "0003_commande_adresse_livraison_commande_note"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="souscommande",
            name="livraison_confirmee_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Litige",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "motif",
                    models.CharField(
                        choices=[
                            ("non_recue", "Commande non reçue"),
                            ("non_conforme", "Article non conforme à l'annonce"),
                            ("incomplete", "Commande incomplète"),
                            ("autre", "Autre"),
                        ],
                        max_length=16,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("ouvert", "Ouvert"),
                            ("en_instruction", "En instruction"),
                            ("tranche_acheteur", "Tranché en faveur de l'acheteur"),
                            ("tranche_marchand", "Tranché en faveur du marchand"),
                            ("partage", "Tranché : remboursement partiel"),
                        ],
                        db_index=True,
                        default="ouvert",
                        max_length=20,
                    ),
                ),
                (
                    "montant_rembourse",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                ("decision", models.TextField(blank=True)),
                ("tranche_le", models.DateTimeField(blank=True, null=True)),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="marketplace.boutique",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sous_commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="litiges",
                        to="orders.souscommande",
                    ),
                ),
                (
                    "tranche_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "litige",
                "ordering": ["-cree_le"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_all_tenants", django.db.models.manager.Manager()),
            ],
        ),
    ]
