# Generated by Django 5.2.17 on 2026-09-30 09:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0007_confiance_et_versement"),
        ("orders", "0004_confiance_et_versement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="souscommande",
            name="expediee_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="souscommande",
            name="mode_paiement",
            field=models.CharField(
                choices=[
                    (
                        "prepaye",
                        "Prépayée — en séquestre jusqu'à la livraison confirmée",
                    ),
                    ("livraison", "Payée à la livraison"),
                ],
                default="prepaye",
                max_length=12,
            ),
        ),
        migrations.AddConstraint(
            model_name="litige",
            constraint=models.UniqueConstraint(
                condition=models.Q(("etat__in", ["ouvert", "en_instruction"])),
                fields=("sous_commande",),
                name="un_litige_en_cours_par_sous_commande",
            ),
        ),
    ]
