# Generated by Django 5.2.17 on 2026-10-01 07:21

import apps.core.uuid7
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0008_avis_au_gerant"),
        ("orders", "0005_sequestre_et_confirmation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AvisCommande",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "numero",
                    models.CharField(help_text="Figé à l'envoi.", max_length=20),
                ),
                (
                    "etat",
                    models.CharField(
                        choices=[("envoye", "Envoyé"), ("echec", "Non parti")],
                        max_length=8,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=128)),
                ("erreur", models.CharField(blank=True, max_length=255)),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="marketplace.boutique",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destinataire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sous_commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avis",
                        to="orders.souscommande",
                    ),
                ),
            ],
            options={
                "verbose_name": "avis de commande",
                "verbose_name_plural": "avis de commande",
                "ordering": ["cree_le"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sous_commande", "destinataire"),
                        name="un_avis_par_part_et_destinataire",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_all_tenants", django.db.models.manager.Manager()),
            ],
        ),
    ]
