# Generated by Django 5.2.17 on 2026-09-07 21:05

import apps.accounts.models
import apps.core.uuid7
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appartenance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                ("depuis", models.DateField(default=django.utils.timezone.localdate)),
                ("jusqu_a", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "appartenance",
            },
        ),
        migrations.CreateModel(
            name="DossierKyc",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_piece",
                    models.CharField(
                        choices=[
                            ("CNI", "Carte nationale d'identité"),
                            ("PASSEPORT", "Passeport"),
                            ("RCCM", "Registre du commerce"),
                            ("NIU", "Numéro identifiant unique"),
                        ],
                        max_length=16,
                    ),
                ),
                ("numero", models.CharField(max_length=64)),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("valide", "Validé"),
                            ("rejete", "Rejeté"),
                        ],
                        default="en_attente",
                        max_length=16,
                    ),
                ),
                ("verifie_le", models.DateTimeField(blank=True, null=True)),
                ("motif_rejet", models.TextField(blank=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "dossier KYC",
                "verbose_name_plural": "dossiers KYC",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "code",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("libelle", models.CharField(max_length=64)),
                (
                    "portee",
                    models.CharField(
                        choices=[
                            ("boutique", "Boutique"),
                            ("plateforme", "Plateforme"),
                        ],
                        default="boutique",
                        max_length=16,
                    ),
                ),
                ("permissions", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "rôle",
                "ordering": ["portee", "code"],
            },
        ),
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        max_length=16,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?[0-9]{8,15}$",
                                "Numéro de téléphone invalide. Format attendu : +237699000000.",
                            )
                        ],
                        verbose_name="téléphone",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("nom_complet", models.CharField(max_length=150)),
                (
                    "code_apporteur",
                    models.CharField(
                        default=apps.accounts.models.generer_code_apporteur,
                        editable=False,
                        help_text="Code de parrainage, immuable pour la vie du compte.",
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("telephone_verifie", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False, verbose_name="accès à l'administration"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "utilisateur",
                "verbose_name_plural": "utilisateurs",
                "ordering": ["nom_complet"],
            },
        ),
    ]
