# Generated by Django 5.2.17 on 2026-09-07 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appartenance",
            name="boutique",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appartenances",
                to="marketplace.boutique",
            ),
        ),
        migrations.AddField(
            model_name="appartenance",
            name="utilisateur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appartenances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dossierkyc",
            name="boutique",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dossiers_kyc",
                to="marketplace.boutique",
            ),
        ),
        migrations.AddField(
            model_name="dossierkyc",
            name="utilisateur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dossiers_kyc",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dossierkyc",
            name="verifie_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appartenance",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appartenances",
                to="accounts.role",
            ),
        ),
        migrations.AddConstraint(
            model_name="appartenance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("actif", True)),
                fields=("utilisateur", "boutique", "role"),
                name="appartenance_unique_active",
            ),
        ),
    ]
