# Generated by Django 5.2.17 on 2026-09-29 12:52

import apps.core.uuid7
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RolePlateforme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                ("depuis", models.DateField(default=django.utils.timezone.localdate)),
                ("jusqu_a", models.DateField(blank=True, null=True)),
                (
                    "motif",
                    models.CharField(
                        blank=True,
                        help_text="Pourquoi cette personne exploite le marché. Utile le jour où on se le demande.",
                        max_length=300,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="porteurs_plateforme",
                        to="accounts.role",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles_plateforme",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "rôle plateforme",
                "verbose_name_plural": "rôles plateforme",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("actif", True)),
                        fields=("utilisateur", "role"),
                        name="role_plateforme_unique_actif",
                    )
                ],
            },
        ),
    ]
