"""Le dossier KYC devient une attestation : ce que l'administrateur a vu, pas une copie.

Pays émetteur, date d'expiration, nom lu, mode de vérification, empreinte SHA-256 du document
reçu, déclarant et vérificateur — et la règle des quatre yeux posée aussi en base
(`kyc_quatre_yeux`). Le numéro de pièce cesse d'être gardé en clair : une empreinte à clé
(HMAC) et ses quatre derniers caractères le remplacent. Voir `apps/accounts/models.DossierKyc`
et `apps/confiance/verification.py`.
"""

# Generated by Django 5.2.17 on 2026-09-30 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def numeros_en_empreintes(apps, schema_editor):
    # La fonction vivante, pas une copie : l'empreinte doit être exactement celle que le code
    # recalculera pour comparer.
    from apps.confiance.verification import empreinte_numero, fin_de_numero

    DossierKyc = apps.get_model("accounts", "DossierKyc")
    for d in DossierKyc.objects.all():
        d.numero_empreinte = empreinte_numero(d.numero)
        d.numero_fin = fin_de_numero(d.numero)
        d.save(update_fields=["numero_empreinte", "numero_fin"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_role_plateforme"),
        ("marketplace", "0007_confiance_et_versement"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dossierkyc",
            options={
                "ordering": ["-cree_le"],
                "verbose_name": "dossier KYC",
                "verbose_name_plural": "dossiers KYC",
            },
        ),
        migrations.AddField(
            model_name="dossierkyc",
            name="copie",
            field=models.CharField(
                blank=True,
                help_text="Chemin de la copie dans le stockage persistant désigné. Vide par défaut, et c'est voulu.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="dossierkyc",
            name="declare_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="déclaré par",
            ),
        ),
        migrations.AddField(
            model_name="dossierkyc",
            name="empreinte",
            field=models.CharField(
                blank=True,
                help_text="Du document reçu, s'il y en a eu un : la preuve qu'on a vu celui-là, sans le garder.",
                max_length=64,
                verbose_name="empreinte SHA-256",
            ),
        ),
        migrations.AddField(
            model_name="dossierkyc",
            name="expire_le",
            field=models.DateField(
                blank=True,
                help_text="Vide : pièce sans échéance (RCCM, NIU).",
                null=True,
                verbose_name="date d'expiration",
            ),
        ),
        migrations.AddField(
            model_name="dossierkyc",
            name="mode_verification",
            field=models.CharField(
                choices=[
                    ("presentiel", "Original vu en présentiel"),
                    ("visio", "Original vu en visio"),
                    ("document_recu", "Document reçu, puis supprimé"),
                    ("appel", "Appel de vérification"),
                ],
                default="presentiel",
                max_length=16,
                verbose_name="mode de vérification",
            ),
        ),
        migrations.AddField(
            model_name="dossierkyc",
            name="nom_lu",
            field=models.CharField(
                blank=True,
                help_text="Recopié de la pièce, pas du compte : c'est à lui qu'on compare le titulaire du compte de versement.",
                max_length=160,
                verbose_name="nom tel qu'il figure",
            ),
        ),
        migrations.AddField(
            model_name="dossierkyc",
            name="numero_empreinte",
            field=models.CharField(
                db_index=True,
                default="",
                help_text="HMAC-SHA256 du numéro normalisé : compare sans révéler. Le numéro lui-même n'est pas gardé.",
                max_length=64,
                verbose_name="empreinte du numéro",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dossierkyc",
            name="numero_fin",
            field=models.CharField(
                blank=True,
                help_text="Les quatre derniers caractères, pour l'affichage masqué.",
                max_length=4,
                verbose_name="fin du numéro",
            ),
        ),
        migrations.AddField(
            model_name="dossierkyc",
            name="pays",
            field=models.CharField(
                default="CM",
                help_text="Code ISO à deux lettres.",
                max_length=2,
                verbose_name="pays émetteur",
            ),
        ),
        migrations.AlterField(
            model_name="dossierkyc",
            name="boutique",
            field=models.ForeignKey(
                blank=True,
                help_text="La boutique pour laquelle la pièce a été présentée.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dossiers_kyc",
                to="marketplace.boutique",
            ),
        ),
        migrations.AlterField(
            model_name="dossierkyc",
            name="etat",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente"),
                    ("valide", "Validé"),
                    ("rejete", "Rejeté"),
                ],
                db_index=True,
                default="en_attente",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="dossierkyc",
            name="type_piece",
            field=models.CharField(
                choices=[
                    ("CNI", "Carte nationale d'identité"),
                    ("PASSEPORT", "Passeport"),
                    ("CARTE_CONSULAIRE", "Carte consulaire"),
                    ("TITRE_SEJOUR", "Titre de séjour"),
                    ("RCCM", "RCCM — immatriculation ou déclaration d'entreprenant"),
                    ("NIU", "Numéro d'identifiant unique (NIU)"),
                    ("NIF", "Numéro d'identification fiscale (NIF)"),
                    ("TELEPHONE", "Appel de vérification du téléphone"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="dossierkyc",
            name="utilisateur",
            field=models.ForeignKey(
                blank=True,
                help_text="La personne dont c'est la pièce (le gérant). Vide pour une pièce de boutique.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dossiers_kyc",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dossierkyc",
            name="verifie_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="vérifié par",
            ),
        ),
        # Les numéros déjà saisis en clair deviennent une empreinte et quatre caractères, puis la
        # colonne en clair disparaît. Irréversible par construction : c'est tout l'objet.
        migrations.RunPython(numeros_en_empreintes, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="dossierkyc",
            name="numero",
        ),
        migrations.AddConstraint(
            model_name="dossierkyc",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("declare_par__isnull", True),
                    ("verifie_par__isnull", True),
                    models.Q(("declare_par", models.F("verifie_par")), _negated=True),
                    _connector="OR",
                ),
                name="kyc_quatre_yeux",
            ),
        ),
        migrations.AddConstraint(
            model_name="dossierkyc",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("utilisateur__isnull", False),
                    ("boutique__isnull", False),
                    _connector="OR",
                ),
                name="kyc_rattache_a_quelqu_un",
            ),
        ),
    ]
