# Generated by Django 5.2.17 on 2026-10-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_kyc_attestation"),
    ]

    operations = [
        migrations.AddField(
            model_name="appartenance",
            name="avis_commandes",
            field=models.BooleanField(
                default=True, verbose_name="prévenir des commandes sur WhatsApp"
            ),
        ),
    ]
