# Generated by Django 5.2.17 on 2026-10-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_avis_commandes"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="libelle_en",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="libellé en anglais"
            ),
        ),
    ]
