# Generated by Django 5.2.17 on 2026-09-09 08:24

import apps.core.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marketplace", "0002_alter_boutique_regime_fiscal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JetonApi",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        help_text="À quoi sert ce jeton. Ex. « Tablette du comptoir 2 ».",
                        max_length=120,
                    ),
                ),
                (
                    "prefixe",
                    models.CharField(editable=False, max_length=16, unique=True),
                ),
                ("empreinte", models.CharField(editable=False, max_length=64)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("dernier_usage_le", models.DateTimeField(blank=True, null=True)),
                ("revoque_le", models.DateTimeField(blank=True, null=True)),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jetons_api",
                        to="marketplace.boutique",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jetons_api",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "jeton d'API",
                "verbose_name_plural": "jetons d'API",
                "ordering": ["-cree_le"],
                "indexes": [
                    models.Index(
                        fields=["utilisateur", "boutique"],
                        name="api_jetonap_utilisa_290faa_idx",
                    )
                ],
            },
        ),
    ]
