# Generated by Django 5.2.17 on 2026-09-07 21:05

import apps.core.uuid7
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeEmplacement",
            fields=[
                (
                    "code",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("libelle", models.CharField(max_length=64)),
                ("loyer_mensuel", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "taux_commission_defaut",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                ("quota_utilisateurs", models.PositiveSmallIntegerField(default=1)),
                ("quota_depots", models.PositiveSmallIntegerField(default=1)),
                (
                    "modules_inclus",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Ex. ["catalogue", "stock", "caisse", "comptabilite"]',
                    ),
                ),
                ("ordre", models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                "verbose_name": "type d'emplacement",
                "verbose_name_plural": "types d'emplacement",
                "ordering": ["ordre"],
            },
        ),
        migrations.CreateModel(
            name="Boutique",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("raison_sociale", models.CharField(max_length=180)),
                (
                    "enseigne",
                    models.CharField(
                        help_text="Nom commercial affiché aux acheteurs.",
                        max_length=120,
                    ),
                ),
                ("slug", models.SlugField(max_length=140, unique=True)),
                (
                    "rccm",
                    models.CharField(blank=True, max_length=64, verbose_name="RCCM"),
                ),
                (
                    "niu",
                    models.CharField(blank=True, max_length=32, verbose_name="NIU"),
                ),
                (
                    "regime_fiscal",
                    models.CharField(
                        choices=[
                            ("liberatoire", "Impôt libératoire (CA < 10 M)"),
                            ("simplifie", "Réel simplifié (CA 50-100 M)"),
                            ("reel_normal", "Réel normal (CA > 100 M)"),
                        ],
                        default="simplifie",
                        max_length=24,
                    ),
                ),
                ("telephone", models.CharField(blank=True, max_length=16)),
                ("ville", models.CharField(default="Douala", max_length=80)),
                ("pays", models.CharField(default="CM", max_length=2)),
                ("devise", models.CharField(default="XAF", max_length=3)),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("candidature", "Candidature"),
                            ("active", "Active"),
                            ("suspendue", "Suspendue"),
                            ("resiliee", "Résiliée"),
                        ],
                        db_index=True,
                        default="candidature",
                        max_length=16,
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "boutique",
                "ordering": ["enseigne"],
            },
        ),
        migrations.CreateModel(
            name="Bail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("debut", models.DateField(default=django.utils.timezone.localdate)),
                ("fin", models.DateField(blank=True, null=True)),
                ("loyer_mensuel", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "depot_garantie",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "taux_commission",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Négocié au contrat ; prime sur le taux du rayon.",
                        max_digits=5,
                    ),
                ),
                ("preavis_jours", models.PositiveSmallIntegerField(default=30)),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("actif", "Actif"),
                            ("resilie", "Résilié"),
                        ],
                        db_index=True,
                        default="brouillon",
                        max_length=16,
                    ),
                ),
                ("motif_resiliation", models.TextField(blank=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="baux",
                        to="marketplace.boutique",
                    ),
                ),
                (
                    "type_emplacement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="marketplace.typeemplacement",
                    ),
                ),
            ],
            options={
                "verbose_name": "bail",
                "verbose_name_plural": "baux",
                "ordering": ["-debut"],
            },
        ),
        migrations.CreateModel(
            name="EtatDesLieux",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("entree", "Entrée"), ("sortie", "Sortie")],
                        max_length=8,
                    ),
                ),
                ("stock_initial", models.JSONField(blank=True, default=list)),
                ("comptes_initiaux", models.JSONField(blank=True, default=list)),
                (
                    "constate_le",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("commentaire", models.TextField(blank=True)),
                (
                    "bail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etats_des_lieux",
                        to="marketplace.bail",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "état des lieux",
                "verbose_name_plural": "états des lieux",
            },
        ),
        migrations.CreateModel(
            name="Rayon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.SlugField(max_length=48, unique=True)),
                ("libelle", models.CharField(max_length=120)),
                (
                    "taux_commission",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Part du montant HT revenant à la plateforme (0.05 = 5 %).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("0.30")),
                        ],
                    ),
                ),
                (
                    "ouvert",
                    models.BooleanField(
                        default=True,
                        help_text="Un rayon fermé n'accepte plus de nouvelles boutiques (arbitrage A8).",
                    ),
                ),
                ("ordre", models.PositiveSmallIntegerField(default=100)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sous_rayons",
                        to="marketplace.rayon",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        help_text="Responsable de rayon (category manager) côté plateforme.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rayons_geres",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "rayon",
                "ordering": ["ordre", "libelle"],
            },
        ),
        migrations.CreateModel(
            name="EmplacementPremium",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("tete_de_gondole", "Tête de gondole"),
                            ("bandeau_rayon", "Bandeau de rayon"),
                            ("accueil", "Page d'accueil"),
                        ],
                        max_length=24,
                    ),
                ),
                ("debut", models.DateField()),
                ("fin", models.DateField()),
                ("tarif", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "boutique_occupante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emplacements_premium",
                        to="marketplace.boutique",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rayon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emplacements_premium",
                        to="marketplace.rayon",
                    ),
                ),
            ],
            options={
                "verbose_name": "emplacement premium",
                "verbose_name_plural": "emplacements premium",
                "ordering": ["-debut"],
            },
        ),
        migrations.AddField(
            model_name="boutique",
            name="rayon_principal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="boutiques",
                to="marketplace.rayon",
            ),
        ),
        migrations.CreateModel(
            name="FactureLoyer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "periode",
                    models.DateField(help_text="Premier jour du mois facturé."),
                ),
                ("montant_ht", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "taux_tva",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.1925"), max_digits=5
                    ),
                ),
                ("echeance", models.DateField()),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("emise", "Émise"),
                            ("payee", "Payée"),
                            ("impayee", "Impayée"),
                            ("annulee", "Annulée"),
                        ],
                        db_index=True,
                        default="emise",
                        max_length=16,
                    ),
                ),
                ("paye_le", models.DateTimeField(blank=True, null=True)),
                (
                    "bail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="factures",
                        to="marketplace.bail",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "facture de loyer",
                "verbose_name_plural": "factures de loyer",
                "ordering": ["-periode"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("bail", "periode"), name="loyer_unique_par_periode"
                    )
                ],
            },
        ),
    ]
