# Generated by Django 5.2.17 on 2026-09-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boutique",
            name="regime_fiscal",
            field=models.CharField(
                choices=[
                    ("igs", "IGS — impôt général synthétique (CA ≤ 50 M)"),
                    ("reel_simplifie", "Réel simplifié (CA 50-100 M)"),
                    ("reel_normal", "Réel normal (CA > 100 M)"),
                ],
                default="reel_simplifie",
                max_length=24,
            ),
        ),
    ]
