# Generated by Django 5.2.17 on 2026-09-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_alter_boutique_regime_fiscal"),
    ]

    operations = [
        migrations.AddField(
            model_name="boutique",
            name="metier",
            field=models.CharField(
                db_index=True,
                default="COMMERCE_GENERAL",
                help_text="Ce que la boutique vend. Détermine le vocabulaire des écrans, les valeurs par défaut et les fonctions activées (apps/marketplace/metiers.py).",
                max_length=32,
                verbose_name="métier",
            ),
        ),
    ]
