# Generated by Django 5.2.17 on 2026-09-09 15:24

import apps.core.uuid7
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_produit_produit_marge_revendeur_entre_0_et_1"),
        ("marketplace", "0003_boutique_metier"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LienMarketing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "libelle",
                    models.CharField(
                        help_text="À quoi sert ce lien : « Flyer marché », « Statut WhatsApp »…",
                        max_length=120,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=16, unique=True)),
                (
                    "code_apporteur",
                    models.CharField(
                        blank=True,
                        help_text="Facultatif : rattache les commandes issues de ce lien à un apporteur.",
                        max_length=12,
                    ),
                ),
                ("clics", models.PositiveIntegerField(default=0)),
                ("actif", models.BooleanField(default=True)),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vide : le lien ouvre la vitrine de la boutique.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liens",
                        to="catalog.variante",
                    ),
                ),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="marketplace.boutique",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "lien marketing",
                "verbose_name_plural": "liens marketing",
                "ordering": ["-cree_le"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_all_tenants", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="IdentiteVisuelle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("logo", models.ImageField(blank=True, upload_to="logos/%Y/%m/")),
                ("couleur_marque", models.CharField(default="#00806A", max_length=7)),
                (
                    "couleur_marque_sombre",
                    models.CharField(default="#2FA98E", max_length=7),
                ),
                ("teinte", models.CharField(default="#E2F0EC", max_length=7)),
                ("teinte_sombre", models.CharField(default="#14251F", max_length=7)),
                ("police", models.CharField(default="systeme", max_length=24)),
                (
                    "motif_ajustement",
                    models.CharField(
                        blank=True,
                        help_text="Ce que la validation a corrigé, et pourquoi. Montré au commerçant.",
                        max_length=255,
                    ),
                ),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="marketplace.boutique",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "identité visuelle",
                "verbose_name_plural": "identités visuelles",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("boutique",), name="une_identite_par_boutique"
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_all_tenants", django.db.models.manager.Manager()),
            ],
        ),
    ]
