# Generated by Django 5.2.17 on 2026-09-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0004_lienmarketing_identitevisuelle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identitevisuelle",
            name="couleur_marque",
            field=models.CharField(default="#00806a", max_length=7),
        ),
        migrations.AlterField(
            model_name="identitevisuelle",
            name="couleur_marque_sombre",
            field=models.CharField(default="#2fa98e", max_length=7),
        ),
        migrations.AlterField(
            model_name="identitevisuelle",
            name="teinte",
            field=models.CharField(default="#e2f0ec", max_length=7),
        ),
        migrations.AlterField(
            model_name="identitevisuelle",
            name="teinte_sombre",
            field=models.CharField(default="#14251f", max_length=7),
        ),
    ]
