# Generated by Django 5.2.17 on 2026-09-29 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0005_alter_identitevisuelle_couleur_marque_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bail",
            name="motif_derogation_commission",
            field=models.CharField(
                blank=True,
                help_text="Obligatoire dès que le taux négocié s'écarte de celui de l'offre. Une faveur commerciale est légitime ; une faveur sans raison écrite ne l'est pas.",
                max_length=300,
            ),
        ),
        migrations.AddConstraint(
            model_name="emplacementpremium",
            constraint=models.CheckConstraint(
                condition=models.Q(("tarif__gt", 0)),
                name="emplacement_premium_tarif_non_nul",
            ),
        ),
    ]
