# Generated by Django 5.2.17 on 2026-09-30 09:14

import apps.core.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0006_garde_fous_conflit_interets"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="boutique",
            name="palier_confiance",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Nouvelle boutique"),
                    (1, "Boutique confirmée"),
                    (2, "Boutique reconnue"),
                    (3, "Boutique établie"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="boutique",
            name="palier_evalue_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="CompteVersement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("pays", models.CharField(default="CM", max_length=2)),
                (
                    "operateur",
                    models.CharField(
                        choices=[
                            ("MTN_MOMO", "MTN Mobile Money"),
                            ("ORANGE_MONEY", "Orange Money"),
                            ("AIRTEL_MONEY", "Airtel Money"),
                            ("MOOV_MONEY", "Moov Money"),
                            ("VIREMENT_BANCAIRE", "Virement bancaire"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        help_text="Numéro Mobile Money au format international, ou IBAN / RIB.",
                        max_length=34,
                    ),
                ),
                (
                    "titulaire",
                    models.CharField(
                        help_text="Nom du titulaire tel qu'il est enregistré chez l'opérateur.",
                        max_length=160,
                    ),
                ),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente de vérification"),
                            ("verifie", "Vérifié"),
                            ("rejete", "Rejeté"),
                            ("retire", "Retiré"),
                        ],
                        db_index=True,
                        default="en_attente",
                        max_length=16,
                    ),
                ),
                ("verifie_le", models.DateTimeField(blank=True, null=True)),
                (
                    "utilisable_le",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fin du délai de carence après vérification.",
                        null=True,
                    ),
                ),
                (
                    "motif",
                    models.CharField(
                        blank=True,
                        help_text="Motif du rejet ou du retrait.",
                        max_length=300,
                    ),
                ),
                ("retire_le", models.DateTimeField(blank=True, null=True)),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comptes_versement",
                        to="marketplace.boutique",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "declare_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "compte de versement",
                "verbose_name_plural": "comptes de versement",
                "ordering": ["-cree_le"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("etat", "verifie")),
                        fields=("boutique",),
                        name="un_compte_de_versement_verifie_par_boutique",
                    )
                ],
            },
        ),
    ]
