# Generated by Django 5.2.17 on 2026-10-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0008_avis_au_gerant"),
    ]

    operations = [
        migrations.AddField(
            model_name="rayon",
            name="libelle_en",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="libellé en anglais"
            ),
        ),
        migrations.AddField(
            model_name="typeemplacement",
            name="libelle_en",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="libellé en anglais"
            ),
        ),
    ]
