# Generated by Django 5.2.17 on 2026-10-09 21:30

import apps.core.uuid7
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0010_libelles_en_referentiels"),
    ]

    operations = [
        migrations.CreateModel(
            name="MesureEmplacement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("jour", models.DateField()),
                ("affichages", models.PositiveIntegerField(default=0)),
                ("clics", models.PositiveIntegerField(default=0)),
                ("commandes", models.PositiveIntegerField(default=0)),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "emplacement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mesures",
                        to="marketplace.emplacementpremium",
                    ),
                ),
            ],
            options={
                "verbose_name": "mesure d'emplacement",
                "verbose_name_plural": "mesures d'emplacement",
                "ordering": ["jour"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("emplacement", "jour"),
                        name="une_mesure_par_emplacement_et_jour",
                    )
                ],
            },
        ),
    ]
