# Generated by Django 5.2.17 on 2026-09-07 21:05

import apps.core.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationSync",
            fields=[
                (
                    "operation_id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("type", models.CharField(db_index=True, max_length=64)),
                ("boutique_id", models.UUIDField(db_index=True)),
                ("charge_utile", models.JSONField()),
                ("horodatage_client", models.DateTimeField()),
                ("recue_le", models.DateTimeField(auto_now_add=True)),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("recue", "Reçue"),
                            ("appliquee", "Appliquée"),
                            ("rejetee", "Rejetée"),
                        ],
                        default="recue",
                        max_length=16,
                    ),
                ),
                ("resultat", models.JSONField(blank=True, null=True)),
                ("erreur", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "opération de synchronisation",
                "verbose_name_plural": "opérations de synchronisation",
                "ordering": ["-horodatage_client"],
            },
        ),
        migrations.CreateModel(
            name="Consentement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "finalite",
                    models.CharField(
                        choices=[
                            ("marketing_sms", "Sollicitations commerciales par SMS"),
                            (
                                "marketing_whatsapp",
                                "Sollicitations commerciales par WhatsApp",
                            ),
                            (
                                "marketing_email",
                                "Sollicitations commerciales par courriel",
                            ),
                            (
                                "partage_cabinet",
                                "Partage des données comptables avec le cabinet partenaire",
                            ),
                            (
                                "scoring_credit",
                                "Analyse des données de vente à des fins d'octroi de financement",
                            ),
                        ],
                        max_length=64,
                    ),
                ),
                ("accorde", models.BooleanField()),
                ("horodatage", models.DateTimeField(auto_now_add=True)),
                ("revoque_le", models.DateTimeField(blank=True, null=True)),
                ("preuve", models.JSONField(blank=True, default=dict)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consentements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "consentement",
                "verbose_name_plural": "registre des consentements",
                "ordering": ["-horodatage"],
                "indexes": [
                    models.Index(
                        fields=["utilisateur", "finalite"],
                        name="core_consen_utilisa_8fb22e_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EntreeAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("horodatage", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("boutique_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("creation", "Création"),
                            ("modification", "Modification"),
                            ("suppression", "Suppression"),
                            ("lecture_sensible", "Lecture de données sensibles"),
                            ("acces_transverse", "Accès transverse plateforme"),
                        ],
                        max_length=32,
                    ),
                ),
                ("objet_type", models.CharField(max_length=128)),
                ("objet_id", models.CharField(blank=True, max_length=64)),
                ("avant", models.JSONField(blank=True, null=True)),
                ("apres", models.JSONField(blank=True, null=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "acteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "entrée d'audit",
                "verbose_name_plural": "journal d'audit",
                "ordering": ["-horodatage"],
                "indexes": [
                    models.Index(
                        fields=["objet_type", "objet_id"],
                        name="core_entree_objet_t_8dc35b_idx",
                    )
                ],
            },
        ),
    ]
