# Generated by Django 5.2.17 on 2026-09-29 12:50

import apps.core.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_table_de_cache"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccesPlateforme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("horodatage", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "boutique_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Boutique consultée, si l'accès en visait une. Vide pour une vue d'ensemble.",
                        null=True,
                    ),
                ),
                (
                    "ecran",
                    models.CharField(
                        help_text="Chemin ou nom de vue, pour retrouver quoi.",
                        max_length=120,
                    ),
                ),
                (
                    "motif",
                    models.CharField(
                        help_text="Pourquoi. Sans défaut : on doit le dire.",
                        max_length=300,
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        help_text="PROTECT : on ne supprime pas quelqu'un dont on garde les accès en mémoire.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acces_plateforme",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "accès plateforme",
                "verbose_name_plural": "journal des accès plateforme",
                "ordering": ["-horodatage"],
                "indexes": [
                    models.Index(
                        fields=["utilisateur", "-horodatage"],
                        name="core_accesp_utilisa_cdcc4e_idx",
                    )
                ],
            },
        ),
    ]
