# Generated by Django 5.2.17 on 2026-09-07 21:05

import apps.core.uuid7
import django.db.models.manager
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompteBoutique",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("numero", models.CharField(max_length=12)),
                ("intitule", models.CharField(max_length=180)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("passif", "Passif"),
                            ("charge", "Charge"),
                            ("produit", "Produit"),
                        ],
                        max_length=12,
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "compte",
                "ordering": ["numero"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_all_tenants", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="CompteGeneral",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("numero", models.CharField(max_length=12)),
                ("intitule", models.CharField(max_length=180)),
                ("classe", models.PositiveSmallIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("passif", "Passif"),
                            ("charge", "Charge"),
                            ("produit", "Produit"),
                        ],
                        max_length=12,
                    ),
                ),
                ("collectif", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "compte du plan",
                "verbose_name_plural": "comptes du plan",
                "ordering": ["numero"],
            },
        ),
        migrations.CreateModel(
            name="DeclarationTva",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "periode",
                    models.DateField(help_text="Premier jour du mois déclaré."),
                ),
                (
                    "collectee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "deductible",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "credit_anterieur",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "etat",
                    models.CharField(
                        choices=[("brouillon", "Brouillon"), ("deposee", "Déposée")],
                        default="brouillon",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "verbose_name": "déclaration de TVA",
                "verbose_name_plural": "déclarations de TVA",
                "ordering": ["-periode"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_all_tenants", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="EcritureComptable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "date_ecriture",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                (
                    "piece",
                    models.CharField(
                        help_text="Séquence continue par journal et exercice.",
                        max_length=32,
                    ),
                ),
                ("libelle", models.CharField(max_length=255)),
                ("validee", models.BooleanField(db_index=True, default=False)),
                (
                    "origine_type",
                    models.CharField(
                        blank=True,
                        help_text='Traçabilité descendante : "pos.Ticket", "orders.SousCommande"…',
                        max_length=64,
                    ),
                ),
                ("origine_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "écriture comptable",
                "verbose_name_plural": "écritures comptables",
                "ordering": ["-date_ecriture", "-cree_le"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_all_tenants", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Exercice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("debut", models.DateField()),
                ("fin", models.DateField()),
                (
                    "etat",
                    models.CharField(
                        choices=[("ouvert", "Ouvert"), ("cloture", "Clôturé")],
                        default="ouvert",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "verbose_name": "exercice",
                "ordering": ["-debut"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_all_tenants", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("VTE", "Journal des ventes"),
                            ("ACH", "Journal des achats"),
                            ("BQE", "Journal de banque"),
                            ("CAI", "Journal de caisse"),
                            ("PAI", "Journal de paie"),
                            ("STK", "Journal des stocks"),
                            ("OD", "Opérations diverses"),
                        ],
                        max_length=8,
                    ),
                ),
                ("libelle", models.CharField(max_length=120)),
            ],
            options={
                "verbose_name": "journal",
                "ordering": ["code"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_all_tenants", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="LigneEcriture",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("libelle", models.CharField(blank=True, max_length=255)),
                (
                    "debit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "lettrage",
                    models.CharField(blank=True, db_index=True, max_length=16),
                ),
            ],
            options={
                "verbose_name": "ligne d'écriture",
                "verbose_name_plural": "lignes d'écriture",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_all_tenants", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="PlanComptable",
            fields=[
                (
                    "code",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("libelle", models.CharField(max_length=120)),
                ("version", models.CharField(default="2018", max_length=16)),
            ],
            options={
                "verbose_name": "plan comptable",
                "verbose_name_plural": "plans comptables",
            },
        ),
    ]
