# Generated by Django 5.2.17 on 2026-09-07 21:05

import apps.core.uuid7
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marketplace", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prestataire",
            fields=[
                (
                    "code",
                    models.CharField(max_length=24, primary_key=True, serialize=False),
                ),
                ("libelle", models.CharField(max_length=64)),
                ("actif", models.BooleanField(default=True)),
                (
                    "taux_frais",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.016"),
                        help_text="1,6 % par défaut.",
                        max_digits=5,
                    ),
                ),
                (
                    "prefixes_numero",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Ex. ["67", "650", "651"] pour le routage automatique.',
                    ),
                ),
            ],
            options={
                "verbose_name": "prestataire de paiement",
                "verbose_name_plural": "prestataires de paiement",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="PortefeuilleMarchand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "solde_disponible",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "solde_bloque",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                ("numero_momo", models.CharField(blank=True, max_length=16)),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="marketplace.boutique",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "portefeuille marchand",
                "verbose_name_plural": "portefeuilles marchands",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_all_tenants", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="MouvementPortefeuille",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("type", models.CharField(max_length=32)),
                ("montant", models.DecimalField(decimal_places=2, max_digits=16)),
                ("solde_apres", models.DecimalField(decimal_places=2, max_digits=16)),
                ("origine_type", models.CharField(blank=True, max_length=64)),
                ("origine_id", models.UUIDField(blank=True, null=True)),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="marketplace.boutique",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "portefeuille",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mouvements",
                        to="payments.portefeuillemarchand",
                    ),
                ),
            ],
            options={
                "verbose_name": "mouvement de portefeuille",
                "verbose_name_plural": "mouvements de portefeuille",
                "ordering": ["-cree_le"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_all_tenants", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Sequestre",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("montant", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("bloque", "Bloqué"),
                            ("libere", "Libéré"),
                            ("rembourse", "Remboursé"),
                        ],
                        db_index=True,
                        default="bloque",
                        max_length=16,
                    ),
                ),
                ("libere_le", models.DateTimeField(blank=True, null=True)),
                ("motif", models.CharField(blank=True, max_length=255)),
                (
                    "commande",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sequestre",
                        to="orders.commande",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "séquestre",
                "ordering": ["-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "sens",
                    models.CharField(
                        choices=[
                            ("encaissement", "Encaissement"),
                            ("versement", "Versement"),
                            ("remboursement", "Remboursement"),
                        ],
                        max_length=16,
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=14)),
                ("numero_payeur", models.CharField(blank=True, max_length=16)),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("initiee", "Initiée"),
                            ("reussie", "Réussie"),
                            ("echouee", "Échouée"),
                            ("expiree", "Expirée"),
                        ],
                        db_index=True,
                        default="initiee",
                        max_length=16,
                    ),
                ),
                ("reference_externe", models.CharField(blank=True, max_length=120)),
                (
                    "cle_idempotence",
                    models.CharField(
                        help_text="Unicité globale : protection principale contre le double débit.",
                        max_length=120,
                        unique=True,
                    ),
                ),
                ("charge_utile_psp", models.JSONField(blank=True, default=dict)),
                (
                    "commande",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="orders.commande",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prestataire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="payments.prestataire",
                    ),
                ),
            ],
            options={
                "verbose_name": "transaction",
                "ordering": ["-cree_le"],
            },
        ),
    ]
