# Generated by Django 5.2.17 on 2026-09-07 21:05

import apps.core.uuid7
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("marketplace", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Depot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("libelle", models.CharField(max_length=120)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("boutique", "Point de vente"),
                            ("reserve", "Réserve"),
                            (
                                "entrepot_plateforme",
                                "Entrepôt mutualisé de la plateforme",
                            ),
                        ],
                        default="boutique",
                        max_length=24,
                    ),
                ),
                ("adresse", models.CharField(blank=True, max_length=255)),
                ("actif", models.BooleanField(default=True)),
                ("principal", models.BooleanField(default=False)),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="marketplace.boutique",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "dépôt",
                "ordering": ["libelle"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_all_tenants", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("nom", models.CharField(max_length=180)),
                ("contact", models.CharField(blank=True, max_length=120)),
                ("telephone", models.CharField(blank=True, max_length=16)),
                ("niu", models.CharField(blank=True, max_length=32)),
                ("delai_paiement_jours", models.PositiveSmallIntegerField(default=0)),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="marketplace.boutique",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "fournisseur",
                "ordering": ["nom"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_all_tenants", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Inventaire",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "etat",
                    models.CharField(
                        choices=[("brouillon", "Brouillon"), ("valide", "Validé")],
                        default="brouillon",
                        max_length=16,
                    ),
                ),
                ("valide_le", models.DateTimeField(blank=True, null=True)),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="marketplace.boutique",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "depot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventaires",
                        to="inventory.depot",
                    ),
                ),
            ],
            options={
                "verbose_name": "inventaire",
                "ordering": ["-date"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_all_tenants", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="LigneInventaire",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("qte_theorique", models.DecimalField(decimal_places=4, max_digits=14)),
                ("qte_comptee", models.DecimalField(decimal_places=4, max_digits=14)),
                ("motif", models.CharField(blank=True, max_length=255)),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="marketplace.boutique",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inventaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="inventory.inventaire",
                    ),
                ),
                (
                    "variante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.variante",
                    ),
                ),
            ],
            options={
                "verbose_name": "ligne d'inventaire",
                "verbose_name_plural": "lignes d'inventaire",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("inventaire", "variante"),
                        name="ligne_inventaire_unique",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_all_tenants", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="MouvementStock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ENTREE", "Entrée"),
                            ("SORTIE", "Sortie"),
                            ("TRANSFERT", "Transfert"),
                            ("AJUSTEMENT", "Ajustement d'inventaire"),
                            ("PERTE", "Perte"),
                            ("CASSE", "Casse"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "quantite",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Signée : positive en entrée, négative en sortie.",
                        max_digits=14,
                    ),
                ),
                (
                    "cout_unitaire",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "cmp_apres",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="CMP historisé : il ne peut pas être recalculé a posteriori.",
                        max_digits=14,
                    ),
                ),
                (
                    "quantite_apres",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "origine_type",
                    models.CharField(
                        blank=True, help_text='Ex. "pos.Ticket".', max_length=64
                    ),
                ),
                ("origine_id", models.UUIDField(blank=True, null=True)),
                (
                    "operation_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Clé d'idempotence de la synchronisation hors ligne.",
                        null=True,
                    ),
                ),
                ("commentaire", models.CharField(blank=True, max_length=255)),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="marketplace.boutique",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "depot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mouvements",
                        to="inventory.depot",
                    ),
                ),
                (
                    "variante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mouvements",
                        to="catalog.variante",
                    ),
                ),
            ],
            options={
                "verbose_name": "mouvement de stock",
                "verbose_name_plural": "mouvements de stock",
                "ordering": ["-cree_le"],
                "indexes": [
                    models.Index(
                        fields=["boutique", "variante", "cree_le"],
                        name="inventory_m_boutiqu_c80f62_idx",
                    ),
                    models.Index(
                        fields=["origine_type", "origine_id"],
                        name="inventory_m_origine_d92e9b_idx",
                    ),
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_all_tenants", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="NiveauStock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "quantite",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "cmp",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="coût moyen pondéré",
                    ),
                ),
                (
                    "seuil_alerte",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=0, help_text="Verrou optimiste."
                    ),
                ),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="marketplace.boutique",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "depot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="niveaux",
                        to="inventory.depot",
                    ),
                ),
                (
                    "variante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="niveaux",
                        to="catalog.variante",
                    ),
                ),
            ],
            options={
                "verbose_name": "niveau de stock",
                "verbose_name_plural": "niveaux de stock",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("depot", "variante"),
                        name="niveau_unique_depot_variante",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_all_tenants", django.db.models.manager.Manager()),
            ],
        ),
    ]
