# Generated by Django 5.2.17 on 2026-09-09 15:07

import apps.core.uuid7
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_produit_produit_marge_revendeur_entre_0_et_1"),
        ("inventory", "0001_initial"),
        ("marketplace", "0003_boutique_metier"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LotStock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "numero",
                    models.CharField(
                        blank=True,
                        help_text="Numéro de lot du fabricant. Vide quand seule la date compte.",
                        max_length=64,
                    ),
                ),
                ("date_peremption", models.DateField(db_index=True)),
                (
                    "quantite",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="marketplace.boutique",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "depot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lots",
                        to="inventory.depot",
                    ),
                ),
                (
                    "variante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lots",
                        to="catalog.variante",
                    ),
                ),
            ],
            options={
                "verbose_name": "lot",
                "verbose_name_plural": "lots",
                "ordering": ["date_peremption", "numero"],
                "indexes": [
                    models.Index(
                        fields=["boutique", "date_peremption"],
                        name="inventory_l_boutiqu_396303_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("depot", "variante", "numero", "date_peremption"),
                        name="lot_unique",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_all_tenants", django.db.models.manager.Manager()),
            ],
        ),
    ]
