# Generated by Django 5.2.17 on 2026-09-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_lotstock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mouvementstock",
            name="type",
            field=models.CharField(
                choices=[
                    ("ENTREE", "Entrée"),
                    ("SORTIE", "Sortie"),
                    ("TRANSFERT", "Transfert"),
                    ("AJUSTEMENT", "Ajustement d'inventaire"),
                    ("PERTE", "Perte"),
                    ("CASSE", "Casse"),
                    ("PRODUCTION", "Production"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
    ]
