# Generated by Django 5.2.17 on 2026-09-14 08:46

import apps.core.uuid7
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_variante_garantie_mois_variante_suivi_unitaire"),
        ("inventory", "0003_alter_mouvementstock_type"),
        ("marketplace", "0005_alter_identitevisuelle_couleur_marque_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NumeroSerie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "numero",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="numéro de série"
                    ),
                ),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("en_stock", "En stock"),
                            ("vendu", "Vendu"),
                            ("atelier", "À l'atelier"),
                            ("sorti", "Sorti du parc"),
                        ],
                        db_index=True,
                        default="en_stock",
                        max_length=16,
                    ),
                ),
                ("recu_le", models.DateField(default=django.utils.timezone.localdate)),
                ("vendu_le", models.DateTimeField(blank=True, null=True)),
                (
                    "garantie_fin",
                    models.DateField(
                        blank=True,
                        help_text="Échéance figée le jour de la vente. Raccourcir la garantie du catalogue ne doit pas raccourcir celles déjà vendues.",
                        null=True,
                    ),
                ),
                ("ticket_id", models.UUIDField(blank=True, null=True)),
                ("ticket_numero", models.CharField(blank=True, max_length=32)),
                ("client", models.CharField(blank=True, max_length=180)),
                ("commentaire", models.CharField(blank=True, max_length=255)),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="marketplace.boutique",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "depot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exemplaires",
                        to="inventory.depot",
                    ),
                ),
                (
                    "variante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exemplaires",
                        to="catalog.variante",
                    ),
                ),
            ],
            options={
                "verbose_name": "exemplaire",
                "verbose_name_plural": "exemplaires",
                "ordering": ["-recu_le", "numero"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_all_tenants", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="PassageAtelier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("entre_le", models.DateTimeField(default=django.utils.timezone.now)),
                ("motif", models.CharField(max_length=255)),
                (
                    "sous_garantie",
                    models.BooleanField(
                        default=False,
                        help_text="Figé à l'entrée : c'est la date du dépôt qui décide.",
                    ),
                ),
                ("sorti_le", models.DateTimeField(blank=True, null=True)),
                ("resultat", models.CharField(blank=True, max_length=255)),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="marketplace.boutique",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exemplaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passages",
                        to="inventory.numeroserie",
                    ),
                ),
            ],
            options={
                "verbose_name": "passage à l'atelier",
                "verbose_name_plural": "passages à l'atelier",
                "ordering": ["-entre_le"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_all_tenants", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name="numeroserie",
            index=models.Index(
                fields=["boutique", "etat"], name="inventory_n_boutiqu_a9efe4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="numeroserie",
            constraint=models.UniqueConstraint(
                fields=("boutique", "numero"), name="numero_serie_unique_par_boutique"
            ),
        ),
        migrations.AddIndex(
            model_name="passageatelier",
            index=models.Index(
                fields=["boutique", "sorti_le"], name="inventory_p_boutiqu_a0dd6c_idx"
            ),
        ),
    ]
