# Generated by Django 5.2.17 on 2026-09-07 21:05

import apps.core.uuid7
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marketplace", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("libelle", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enfants",
                        to="catalog.categorie",
                    ),
                ),
                (
                    "rayon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="categories",
                        to="marketplace.rayon",
                    ),
                ),
            ],
            options={
                "verbose_name": "catégorie",
                "ordering": ["libelle"],
            },
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("sku", models.CharField(max_length=64)),
                ("libelle", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "unite",
                    models.CharField(
                        choices=[
                            ("U", "Unité"),
                            ("KG", "Kilogramme"),
                            ("L", "Litre"),
                            ("M", "Mètre"),
                        ],
                        default="U",
                        max_length=4,
                    ),
                ),
                (
                    "regime_tva",
                    models.CharField(
                        choices=[
                            ("normal", "Taux normal (19,25 %)"),
                            ("exonere", "Exonéré"),
                            ("hors_champ", "Hors champ"),
                        ],
                        default="normal",
                        max_length=16,
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                (
                    "revente_autorisee",
                    models.BooleanField(
                        default=False,
                        help_text="Le produit peut être poussé par les revendeurs affiliés.",
                    ),
                ),
                (
                    "marge_revendeur",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="Part du HT laissée au revendeur (0.10 = 10 %). Prise sur la marge du marchand.",
                        max_digits=5,
                    ),
                ),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="marketplace.boutique",
                    ),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="produits",
                        to="catalog.categorie",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "produit",
                "ordering": ["libelle"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_all_tenants", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="MediaProduit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("fichier", models.ImageField(upload_to="produits/%Y/%m/")),
                ("alt", models.CharField(blank=True, max_length=180)),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="marketplace.boutique",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medias",
                        to="catalog.produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "média produit",
                "verbose_name_plural": "médias produit",
                "ordering": ["ordre"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_all_tenants", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ProduitReference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code_barres", models.CharField(max_length=32, unique=True)),
                ("libelle", models.CharField(max_length=200)),
                ("marque", models.CharField(blank=True, max_length=120)),
                ("fiche", models.JSONField(blank=True, default=dict)),
                (
                    "categorie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="references",
                        to="catalog.categorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "référence produit (plateforme)",
                "verbose_name_plural": "références produit (plateforme)",
                "ordering": ["libelle"],
            },
        ),
        migrations.AddField(
            model_name="produit",
            name="reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="produits",
                to="catalog.produitreference",
            ),
        ),
        migrations.CreateModel(
            name="Variante",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("sku", models.CharField(max_length=64)),
                ("code_barres", models.CharField(blank=True, max_length=32)),
                (
                    "attributs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Ex. {"taille": "42", "couleur": "noir"}',
                    ),
                ),
                (
                    "prix_vente",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "prix_barre",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="marketplace.boutique",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variantes",
                        to="catalog.produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "variante",
                "ordering": ["produit__libelle", "sku"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_all_tenants", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="categorie",
            constraint=models.UniqueConstraint(
                fields=("rayon", "slug"), name="categorie_slug_unique_par_rayon"
            ),
        ),
        migrations.AddConstraint(
            model_name="produit",
            constraint=models.UniqueConstraint(
                fields=("boutique", "sku"), name="produit_sku_unique_par_boutique"
            ),
        ),
        migrations.AddConstraint(
            model_name="variante",
            constraint=models.UniqueConstraint(
                fields=("boutique", "sku"), name="variante_sku_unique_par_boutique"
            ),
        ),
        migrations.AddConstraint(
            model_name="variante",
            constraint=models.CheckConstraint(
                condition=models.Q(("prix_vente__gte", 0)), name="variante_prix_positif"
            ),
        ),
    ]
