# Generated by Django 5.2.17 on 2026-09-07 21:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("marketplace", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="produit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("marge_revendeur__gte", 0), ("marge_revendeur__lte", 1)
                ),
                name="produit_marge_revendeur_entre_0_et_1",
            ),
        ),
    ]
