# Generated by Django 5.2.17 on 2026-09-10 13:34

import apps.core.uuid7
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_produit_produit_marge_revendeur_entre_0_et_1"),
        ("marketplace", "0005_alter_identitevisuelle_couleur_marque_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recette",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "rendement",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1"),
                        help_text="Combien d'unités une exécution de la fiche produit. Ex. 40 baguettes.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                    ),
                ),
                (
                    "duree_conservation_jours",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Nombre de jours de conservation. Vide si le produit ne périme pas.",
                        null=True,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Mode opératoire, tour de main, température.",
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="marketplace.boutique",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variante",
                    models.OneToOneField(
                        help_text="Le produit fini que cette fiche fabrique.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recette",
                        to="catalog.variante",
                    ),
                ),
            ],
            options={
                "verbose_name": "fiche technique",
                "verbose_name_plural": "fiches techniques",
                "ordering": ["variante__produit__libelle"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_all_tenants", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="LigneRecette",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "quantite",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Quantité pour le rendement complet de la fiche, dans l'unité de l'ingrédient.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                    ),
                ),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="marketplace.boutique",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entre_dans",
                        to="catalog.variante",
                    ),
                ),
                (
                    "recette",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="catalog.recette",
                    ),
                ),
            ],
            options={
                "verbose_name": "ingrédient",
                "verbose_name_plural": "ingrédients",
                "ordering": ["ingredient__produit__libelle"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_all_tenants", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="recette",
            constraint=models.CheckConstraint(
                condition=models.Q(("rendement__gt", 0)),
                name="recette_rendement_positif",
            ),
        ),
        migrations.AddConstraint(
            model_name="lignerecette",
            constraint=models.UniqueConstraint(
                fields=("recette", "ingredient"),
                name="ligne_recette_unique_par_ingredient",
            ),
        ),
        migrations.AddConstraint(
            model_name="lignerecette",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantite__gt", 0)),
                name="ligne_recette_quantite_positive",
            ),
        ),
    ]
