# Generated by Django 5.2.17 on 2026-09-10 15:15

import apps.core.uuid7
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_recette_lignerecette_and_more"),
        ("marketplace", "0005_alter_identitevisuelle_couleur_marque_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="variante",
            name="reference_constructeur",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Référence d'origine du fabricant. Ex. 90915-YZZD4.",
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="CompatibiliteVehicule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("marque", models.CharField(db_index=True, max_length=60)),
                (
                    "modele",
                    models.CharField(
                        blank=True,
                        help_text="Vide si la pièce va sur toute la marque.",
                        max_length=80,
                    ),
                ),
                (
                    "motorisation",
                    models.CharField(
                        blank=True,
                        help_text="Ex. 1.4 D-4D. Vide si indifférent.",
                        max_length=60,
                    ),
                ),
                (
                    "annee_debut",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("annee_fin", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="marketplace.boutique",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compatibilites",
                        to="catalog.variante",
                    ),
                ),
            ],
            options={
                "verbose_name": "compatibilité véhicule",
                "verbose_name_plural": "compatibilités véhicule",
                "ordering": ["marque", "modele", "annee_debut"],
                "indexes": [
                    models.Index(
                        fields=["boutique", "marque", "modele"],
                        name="catalog_com_boutiqu_9dd107_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("annee_fin__isnull", True),
                            ("annee_debut__isnull", True),
                            ("annee_fin__gte", models.F("annee_debut")),
                            _connector="OR",
                        ),
                        name="compatibilite_annees_dans_l_ordre",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_all_tenants", django.db.models.manager.Manager()),
            ],
        ),
    ]
