# Generated by Django 5.2.17 on 2026-09-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_variante_reference_constructeur_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="sur_ordonnance",
            field=models.BooleanField(
                default=False,
                help_text="Ne se délivre que sur ordonnance, et ne se vend pas en ligne.",
            ),
        ),
    ]
