# Generated by Django 5.2.17 on 2026-09-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_produit_sur_ordonnance"),
    ]

    operations = [
        migrations.AddField(
            model_name="variante",
            name="garantie_mois",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Durée de garantie offerte à l'acheteur, en mois. Zéro : aucune garantie.",
            ),
        ),
        migrations.AddField(
            model_name="variante",
            name="suivi_unitaire",
            field=models.BooleanField(
                default=False,
                help_text="Chaque exemplaire porte un numéro de série ou un IMEI, suivi individuellement.",
            ),
        ),
    ]
