# Generated by Django 5.2.17 on 2026-09-19 20:36

import apps.core.uuid7
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_variante_garantie_mois_variante_suivi_unitaire"),
        ("marketplace", "0005_alter_identitevisuelle_couleur_marque_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Designation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("dci", "Dénomination commune internationale"),
                            ("reference", "Référence d'un autre fabricant"),
                            ("commercial", "Autre nom commercial"),
                        ],
                        default="dci",
                        max_length=16,
                    ),
                ),
                (
                    "valeur",
                    models.CharField(
                        db_index=True,
                        help_text="La désignation telle qu'elle est écrite sur la boîte ou la pièce.",
                        max_length=120,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Qui l'emploie : un laboratoire, un équipementier. Ex. Mann, Bosch.",
                        max_length=120,
                    ),
                ),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="marketplace.boutique",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="designations",
                        to="catalog.variante",
                    ),
                ),
            ],
            options={
                "verbose_name": "désignation",
                "ordering": ["type", "valeur"],
                "indexes": [
                    models.Index(
                        fields=["boutique", "type", "valeur"],
                        name="catalog_des_boutiqu_3e1cc8_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("variante", "type", "valeur"),
                        name="designation_unique_par_variante",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_all_tenants", django.db.models.manager.Manager()),
            ],
        ),
    ]
