# Generated by Django 5.2.17 on 2026-10-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_designation"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorie",
            name="libelle_en",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="libellé en anglais"
            ),
        ),
        migrations.AddField(
            model_name="produit",
            name="description_en",
            field=models.TextField(blank=True, verbose_name="description en anglais"),
        ),
        migrations.AddField(
            model_name="produit",
            name="libelle_en",
            field=models.CharField(
                blank=True,
                help_text="Facultatif : le nom montré aux acheteurs qui lisent le marché en anglais.",
                max_length=200,
                verbose_name="libellé en anglais",
            ),
        ),
        migrations.AddField(
            model_name="produitreference",
            name="libelle_en",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="libellé en anglais"
            ),
        ),
    ]
