# Generated by Django 5.2.17 on 2026-09-07 21:05

import apps.core.uuid7
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Revendeur",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("slug_vitrine", models.SlugField(max_length=80, unique=True)),
                (
                    "etat",
                    models.CharField(
                        choices=[("actif", "Actif"), ("suspendu", "Suspendu")],
                        default="actif",
                        max_length=16,
                    ),
                ),
                (
                    "plafond_remise",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="Remise maximale que le revendeur peut consentir, prise sur sa propre marge.",
                        max_digits=5,
                    ),
                ),
            ],
            options={
                "verbose_name": "revendeur",
                "ordering": ["slug_vitrine"],
            },
        ),
        migrations.CreateModel(
            name="SignalFraude",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("auto_parrainage", "Auto-parrainage"),
                            ("comptes_multiples", "Comptes multiples"),
                            ("commandes_fictives", "Commandes fictives"),
                            ("retours_systematiques", "Retours systématiques"),
                            ("vol_attribution", "Vol d'attribution"),
                        ],
                        max_length=32,
                    ),
                ),
                ("score", models.PositiveSmallIntegerField(default=0)),
                ("preuve", models.JSONField(blank=True, default=dict)),
                ("decision", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "signal de fraude",
                "verbose_name_plural": "signaux de fraude",
                "ordering": ["-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="Apporteur",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=12, unique=True)),
                (
                    "etat",
                    models.CharField(
                        choices=[("actif", "Actif"), ("suspendu", "Suspendu")],
                        db_index=True,
                        default="actif",
                        max_length=16,
                    ),
                ),
                (
                    "kyc_renforce",
                    models.BooleanField(
                        default=False,
                        help_text="Requis au-delà de 500 000 FCFA de gains mensuels (docs/06, §6).",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parrain_n1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="filleuls_n1",
                        to="affiliation.apporteur",
                    ),
                ),
                (
                    "parrain_n2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="filleuls_n2",
                        to="affiliation.apporteur",
                    ),
                ),
                (
                    "utilisateur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apporteur",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "apporteur",
                "ordering": ["-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="Attribution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "cible_type",
                    models.CharField(
                        choices=[
                            ("acheteur", "Acheteur"),
                            ("marchand", "Marchand"),
                            ("revendeur", "Revendeur"),
                        ],
                        max_length=16,
                    ),
                ),
                ("cible_id", models.UUIDField()),
                (
                    "origine",
                    models.CharField(
                        choices=[
                            ("code", "Code saisi explicitement"),
                            ("clic", "Dernier clic non direct"),
                            ("rattachement", "Rattachement permanent du compte"),
                        ],
                        max_length=16,
                    ),
                ),
                ("debut", models.DateTimeField(default=django.utils.timezone.now)),
                ("fin", models.DateTimeField()),
                ("preuve", models.JSONField(blank=True, default=dict)),
                (
                    "apporteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributions",
                        to="affiliation.apporteur",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "attribution",
                "ordering": ["-debut"],
            },
        ),
        migrations.CreateModel(
            name="CatalogueRevendeur",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("marge", models.DecimalField(decimal_places=4, max_digits=5)),
                ("actif", models.BooleanField(default=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revendeurs",
                        to="catalog.variante",
                    ),
                ),
            ],
            options={
                "verbose_name": "produit du catalogue revendeur",
                "verbose_name_plural": "catalogue revendeur",
            },
        ),
        migrations.CreateModel(
            name="Commission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("N1", "Apporteur direct"),
                            ("N2", "Apporteur indirect"),
                            ("REVENDEUR", "Revendeur"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "assiette",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Commission plateforme sur laquelle est prélevée la part.",
                        max_digits=14,
                    ),
                ),
                ("taux", models.DecimalField(decimal_places=4, max_digits=5)),
                ("montant", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("attendue", "Attendue"),
                            ("acquise", "Acquise"),
                            ("payable", "Payable"),
                            ("payee", "Payée"),
                            ("annulee", "Annulée"),
                            ("reprise", "Reprise sur gains futurs"),
                        ],
                        db_index=True,
                        default="attendue",
                        max_length=16,
                    ),
                ),
                ("acquise_le", models.DateTimeField(blank=True, null=True)),
                ("payee_le", models.DateTimeField(blank=True, null=True)),
                (
                    "beneficiaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "commission",
                "ordering": ["-cree_le"],
            },
        ),
    ]
