# Generated by Django 5.2.17 on 2026-09-07 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("affiliation", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="commission",
            name="sous_commande",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commissions",
                to="orders.souscommande",
            ),
        ),
        migrations.AddField(
            model_name="revendeur",
            name="cree_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="revendeur",
            name="utilisateur",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revendeur",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cataloguerevendeur",
            name="revendeur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalogue",
                to="affiliation.revendeur",
            ),
        ),
        migrations.AddField(
            model_name="signalfraude",
            name="apporteur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="signaux_fraude",
                to="affiliation.apporteur",
            ),
        ),
        migrations.AddField(
            model_name="signalfraude",
            name="cree_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="signalfraude",
            name="traite_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="attribution",
            index=models.Index(
                fields=["cible_type", "cible_id"], name="affiliation_cible_t_b6ff0c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="attribution",
            constraint=models.UniqueConstraint(
                fields=("cible_type", "cible_id"),
                name="une_attribution_active_par_cible",
            ),
        ),
        migrations.AddConstraint(
            model_name="commission",
            constraint=models.UniqueConstraint(
                fields=("sous_commande", "beneficiaire", "role"),
                name="commission_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="cataloguerevendeur",
            constraint=models.UniqueConstraint(
                fields=("revendeur", "variante"), name="catalogue_revendeur_unique"
            ),
        ),
    ]
