# Generated by Django 5.2.17 on 2026-09-07 21:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliation", "0002_initial"),
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cataloguerevendeur",
            constraint=models.CheckConstraint(
                condition=models.Q(("marge__gte", 0), ("marge__lte", 1)),
                name="catalogue_revendeur_marge_entre_0_et_1",
            ),
        ),
    ]
