# Generated by Django 5.2.17 on 2026-09-07 21:05

import apps.core.uuid7
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("inventory", "0001_initial"),
        ("marketplace", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionCaisse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("ouverte_le", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "fonds_ouverture",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("fermee_le", models.DateTimeField(blank=True, null=True)),
                (
                    "fonds_compte",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "etat",
                    models.CharField(
                        choices=[("ouverte", "Ouverte"), ("fermee", "Fermée")],
                        db_index=True,
                        default="ouverte",
                        max_length=16,
                    ),
                ),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="marketplace.boutique",
                    ),
                ),
                (
                    "caissier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions_caisse",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "depot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="inventory.depot",
                    ),
                ),
            ],
            options={
                "verbose_name": "session de caisse",
                "verbose_name_plural": "sessions de caisse",
                "ordering": ["-ouverte_le"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_all_tenants", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("numero", models.CharField(max_length=32)),
                ("client_nom", models.CharField(blank=True, max_length=180)),
                ("client_telephone", models.CharField(blank=True, max_length=16)),
                (
                    "total_ht",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "total_tva",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "total_ttc",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("cloture", "Clôturé"),
                            ("annule", "Annulé"),
                        ],
                        db_index=True,
                        default="brouillon",
                        max_length=16,
                    ),
                ),
                ("cloture_le", models.DateTimeField(blank=True, null=True)),
                (
                    "operation_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Clé d'idempotence du mode hors ligne.",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="marketplace.boutique",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="pos.sessioncaisse",
                    ),
                ),
            ],
            options={
                "verbose_name": "ticket",
                "ordering": ["-cree_le"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_all_tenants", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ReglementTicket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "moyen",
                    models.CharField(
                        choices=[
                            ("especes", "Espèces"),
                            ("mobile_money", "Mobile Money"),
                            ("carte", "Carte bancaire"),
                            ("credit", "À crédit"),
                        ],
                        max_length=16,
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=14)),
                ("reference_psp", models.CharField(blank=True, max_length=120)),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="marketplace.boutique",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reglements",
                        to="pos.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "règlement",
                "verbose_name_plural": "règlements",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_all_tenants", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="LigneTicket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "libelle",
                    models.CharField(
                        help_text="Figé à la vente : le produit peut changer.",
                        max_length=200,
                    ),
                ),
                ("quantite", models.DecimalField(decimal_places=4, max_digits=14)),
                ("pu_ttc", models.DecimalField(decimal_places=2, max_digits=12)),
                ("taux_tva", models.DecimalField(decimal_places=4, max_digits=5)),
                (
                    "remise",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="marketplace.boutique",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.variante",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="pos.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "ligne de ticket",
                "verbose_name_plural": "lignes de ticket",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_all_tenants", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("boutique", "numero"), name="ticket_numero_unique"
            ),
        ),
    ]
