# Generated by Django 5.2.17 on 2026-09-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ligneticket",
            name="sur_ordonnance",
            field=models.BooleanField(
                default=False,
                help_text="Figé à la vente, comme le libellé et le prix : un médicament reclassé l'an prochain ne doit pas réécrire l'ordonnancier de cette année.",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="mention_ordonnance",
            field=models.CharField(
                blank=True,
                help_text="Prescripteur et date de l'ordonnance, pour l'ordonnancier.",
                max_length=180,
            ),
        ),
    ]
