# Generated by Django 5.2.17 on 2026-09-29 12:56

import apps.core.uuid7
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0006_garde_fous_conflit_interets"),
        ("pos", "0002_ligneticket_sur_ordonnance_ticket_mention_ordonnance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientCahier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("nom", models.CharField(max_length=180)),
                (
                    "telephone",
                    models.CharField(
                        blank=True,
                        help_text="Facultatif : beaucoup de clients de quartier n'en donnent pas. Sert de clé.",
                        max_length=16,
                    ),
                ),
                (
                    "plafond_credit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Encours maximal autorisé. Zéro signifie « pas de crédit » et non « illimité » : un plafond oublié ne doit pas ouvrir un crédit sans limite.",
                        max_digits=12,
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                ("note", models.CharField(blank=True, max_length=300)),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="marketplace.boutique",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "client du cahier",
                "verbose_name_plural": "clients du cahier",
                "ordering": ["nom"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_all_tenants", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="ticket",
            name="client",
            field=models.ForeignKey(
                blank=True,
                help_text="Renseigné seulement pour une vente au cahier. PROTECT : on ne supprime pas un client dont des ventes portent la trace.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tickets",
                to="pos.clientcahier",
            ),
        ),
        migrations.CreateModel(
            name="ReglementCahier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "moyen",
                    models.CharField(
                        choices=[
                            ("especes", "Espèces"),
                            ("mobile_money", "Mobile Money"),
                            ("carte", "Carte bancaire"),
                        ],
                        max_length=16,
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "recu_le",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("reference_psp", models.CharField(blank=True, max_length=120)),
                ("note", models.CharField(blank=True, max_length=300)),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="marketplace.boutique",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reglements_cahier",
                        to="pos.clientcahier",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "règlement du cahier",
                "verbose_name_plural": "règlements du cahier",
                "ordering": ["-recu_le"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_all_tenants", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name="clientcahier",
            index=models.Index(
                fields=["boutique", "nom"], name="pos_clientc_boutiqu_b14457_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="clientcahier",
            constraint=models.UniqueConstraint(
                condition=models.Q(("telephone", ""), _negated=True),
                fields=("boutique", "telephone"),
                name="client_cahier_telephone_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="reglementcahier",
            index=models.Index(
                fields=["client", "-recu_le"], name="pos_regleme_client__2681ad_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="reglementcahier",
            constraint=models.CheckConstraint(
                condition=models.Q(("montant__gt", 0)),
                name="reglement_cahier_montant_positif",
            ),
        ),
    ]
